### ISSUE TITLE
NullPointerException at UiAutomation.setOnAccessibilityEventListener

### ISSUE THREAD

**Issue by jagan-veeraraghavan** [xiaocong/android-uiautomator-server#30]
If i run the prebuilt apk, in uiautomator python project, it works fine. But If I build and test, I get the following error.

Steps:
 
./gradlew installDebug installDebugAndroidTest

adb shell  am instrument com.github. uiautomator .test/android.support.test.runner.AndroidJUnitRunner"

Error:

I/TestRunner: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.UiAutomation.setOnAccessibilityEventListener(android.app.UiAutomation$OnAccessibilityEventListener)' on a null object reference
                                                   at android.support.test.uiautomator.UiAutomatorBridge.setOnAccessibilityEventListener(UiAutomatorBridge.java:78)
                                                   at android.support.test.uiautomator.QueryController.<init>(QueryController.java:58)
                                                   at android.support.test.uiautomator.UiAutomatorBridge.<init>(UiAutomatorBridge.java:66)
                                                   at android.support.test.uiautomator.InstrumentationUiAutomatorBridge.<init>(InstrumentationUiAutomatorBridge.java:35)
                                                   at android.support.test.uiautomator.UiDevice.<init>(UiDevice.java:106)
                                                   at android.support.test.uiautomator.UiDevice.getInstance(UiDevice.java:269)
                                                   at com.github.uiautomator.stub.Stub.setUp(Stub.kt:57)
                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                   at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
                                                   at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
                                                   at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
                                                   at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
                                                   at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
                                                   at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
                                                   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
                                                   at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
                                                   at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
                                                   at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
                                                   at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
                                                   at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
                                                   at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
                                                   at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                                                   at org.junit.runners.Suite.runChild(Suite.java:128)
                                                   at org.junit.runners.Suite.runChild(Suite.java:27)
                                                   at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
                                                   at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
                                                   at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
                                                   at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
                                                   at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
                                                   at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
                                                   at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
                                                   at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
                                                   at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
                                                   at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
                                                   at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1941)

**Comment by jagan-veeraraghavan** [comment]
Works with -w flag to instrument command
adb shell am instrument -w com.github. uiautomator .test/android.support.test.runner.AndroidJUnitRunner
